name: Debug

on:
  pull_request:
    branches: [sprint-*]

jobs:
  debug:
    name: Debug Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: |
          echo "Base ref: ${{ github.base_ref }}"
          echo "Head ref: ${{ github.head_ref }}"
          echo "isMerged: ${{ github.event.pull_request.merged }}"
          echo "Comits count: ${{ github.event.pull_request.commits }}"
