name: Update minor version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    name: Auto Tag Minor Release
    runs-on: solinas
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump minor version
        run: |
          npm version minor --no-git-tag-version
          
          VERSION=$(jq -r '.version' package.json)
          echo "Version is $VERSION" >> $GITHUB_STEP_SUMMARY
          
          git add package.json
          git commit -m "Set version to $VERSION"

      - name: Push changes
        run: |
          git push origin main
